## Put comments here that give an overall description of what your
## functions do
####### We can input an invertible square matrix in the first function-"makeCacheMatrix"
#       which will give us a list as an output. The output of this function can 
#       be used as the input of the second function- "CacheSolve". The "CacheSolve"
#       function will first check if the inverse matrix has been calculated before and
#       cached in the "i" vector of the first function. If the inverse has not been
#       calculated before, then value of "i" will be NULL. In that case the CacheSolve
#       function will calculate the inverse of the inputted matrix, store it as cache
#       in the "i" vector of the first function and show it as output.
#       If the inverse has already been cached and stored, the function will just
#       just fetch the cached data from first function and show it as output.
#       An additional message will be shown in this case- "getting cached data".
#       Note: 1. The "makeCacheMatrix" function will only take a matrix as input
#             2. The "CacheSolve" function will only take a list as an input, which
#                is the list returned by the "makeCacheMatrix" function.
# 
## Write a short comment describing this function
#  Function"makeCacheMatrix" will only take a matrix as an input (which we assume
#  to be invertible in this assignment. The function will give us an output of a 
#  list containging 4 functions- set(), get(), setinv(), getinv(). The 4 functions would serve the
# the following purposes consecutively- 1. setting the matrix to be inversed,
#                                       2. Getting the value of the matrix inputted,
#                                       3. setting the value of the inverse matrix,
#                                       4. Getting the value of the inverse matrix.
# These function would be called upon in the "CacheSolve" function to perform thier 
# intended tasks.The "x" vector will store the value of the matrix input and "i"
# vector (the vector intended to cache the value of the inverse) will be reset to 
# NULL value everytime we we input something in the makeCacheMatrix() function.

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function(y) {
                x <<- y
                i <<- NULL
        }
        get <- function() x
        setinv <- function(inverse) i <<- inverse 
        getinv <- function() i
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)

}


## Write a short comment describing this function
######## The function will only take a list as an input, which must be the list
#        generated by the first function as an output. The function will then either
#        calculate the inverse of the inputted matrix, or fetch the cached value of
#        the inverse matrix if it has been calculated before.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        i <- x$getinv()
        if(!is.null(i)) {
                message("getting cached data")
                return(i)
        }
        data <- x$get()
        i <- solve(data, ...)
        x$setinv(i)
        i
}
